# Docker script for deploying the payment service
version: '3.8'
services:
sepa-payment-service:
image: sepa-payment:latest
ports:
- "8080:8080"
environment:
- DATABASE_URI=mongodb:#mongo:27017/sepa
depends_on:
- mongo
mongo:
image: mongo:latest
ports:
- "27017:27017"